//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseFirstApproach_1912C1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int std_id { get; set; }
        public string std_name { get; set; }
        public string batch { get; set; }
        public Nullable<int> age { get; set; }
    }
}
